### PR TITLE
ISSUE-65: use 'files' field instead of '.npmignore' file

### PR DESCRIPTION
**Pull request by mrmlnc**
#65

### CODE REVIEW

**Comment by mrmlnc** [comment]
Blocked by https://github.com/npm/cli/issues/2038.

**Comment by hisabimbola** [comment]
Hi @mrmlnc 

any update on this, it seem the update from npm would take a while and currently the latest version deployed is broken and apps that update would also be broken in production systems. So this is pretty critical, it would be good to find a workaround on this

**Comment by mrmlnc** [comment]
Thousands of packages are distributed through npm along with TS tests that come to the user in node modules. Having tests in the package should not break your build if it is configured correctly. This is confirmed by the lack of mass character of the problem.

**Comment by hisabimbola** [comment]
Yes @mrmlnc you correct, we did not exclude node_modules during tests. Thanks for pointing out

**Pull request merged**
